version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-challenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j1gqmno9r5d9"
s3_prefix = "cloud-resume-challenge"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
