AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-challenge

  Sample SAM Template for cloud-resume-challenge

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: True
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  
  MyWebsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketName: hrw-resume-website

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Visitors
      #Tags: 
       # - Tag
      #TimeToLiveSpecification: 
       # TimeToLiveSpecification
      BillingMode: PAY_PER_REQUEST
       # KeySchema: 
      #   - AttributeName: "Visitors"
      #     KeyType: "HASH"
        # - AttributeName: "vc"
        #   KeyType: "RANGE"
      #LocalSecondaryIndexes: 
      #PointInTimeRecoverySpecification: 
       # PointInTimeRecoverySpecification
      #ProvisionedThroughput: 
       # ProvisionedThroughput
      #SSESpecification: 
       # SSESpecification
      #StreamSpecification: 
       # StreamSpecification
      AttributeDefinitions:
        - AttributeName: "VisitorCount"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "VisitorCount"
          KeyType: "HASH"
           # AttributeDefinitions: 
      #   - 
      #     AttributeName: "Visitors"
      #     AttributeType: "N"
      #   # - 
      #   #   AttributeName: "vc"
      #   #   AttributeType: "N"


  MyDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ViewerProtocolPolicy: allow-all
          TargetOriginId: E3BH66PB5KP8H2
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
            QueryString: false
        Origins:
            - DomainName: hunter-walls-resume.com
              Id: E3BH66PB5KP8H2
              CustomOriginConfig:
                OriginProtocolPolicy: match-viewer
        Enabled: "true"
        DefaultRootObject: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join 
              - ""
              - - "arn:aws:s3:::"
                - !Ref MyWebsite
                - /*
      Bucket: !Ref MyWebsite

  PutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Policies: AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /visitor_count
            Method: get
