on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name cloud-resume-challenge --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1j1gqmno9r5d9 --capabilities CAPABILITY_IAM --region us-east-1 

 
      
  api_smoke_test:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 moto requests

      - name: Start local DynamoDB
        run: |
          mkdir /tmp/dynamodb_local
          wget -O /tmp/dynamodb_local/dynamodb_local_latest.zip https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip
          unzip -q /tmp/dynamodb_local/dynamodb_local_latest.zip -d /tmp/dynamodb_local
          java -Djava.library.path=/tmp/dynamodb_local/DynamoDBLocal_lib -jar /tmp/dynamodb_local/DynamoDBLocal.jar -inMemory &

      - name: Run tests
        run: |
          python -m unittest discover Lambda

      - name: Test API with requests
        run: |
          python app-test.py
